#index:
#    path: /
#    controller: App\Controller\DefaultController::index

default:
  path: /
  controller: App\Controller\HomeController::index

admin:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /admin/referential
    permanent: true

admin_referential:
  resource: './routes/admin/referential.yaml'
  prefix: /admin/referential

api:
  resource: './routes/api.yaml'
  prefix: /{version}/api

