#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin_referential:
  resource: './routes/admin/referential.yaml'
  prefix: /admin/referential

api:
  resource: './routes/api.yaml'
  prefix: /{version}/api

