admin_referential_index:
  path: /
  controller: App\Controller\Admin\ReferentialController::index

admin_referential_list:
  path: list
  controller: App\Controller\Admin\ReferentialController::list

admin_referential_add:
  path: add
  controller: App\Controller\Admin\ReferentialController::add

admin_referential_edit:
  path: edit/{referential}
  controller: App\Controller\Admin\ReferentialController::edit

admin_referential_manage:
  path: /manage/{referential}
  controller: App\Controller\Admin\ReferentialController::manage

admin_referential_details:
  path: /details/{referential}
  controller: App\Controller\Admin\ReferentialController::details
